### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by PySimpleGUI** [pizzaspren/FastWorldCreator#1]
Hi there!  I noticed you've got a GUI...

It's uncommon for Python programs to have a GUI, so it's extra special when you run into Python code on GitHub that has a GUI. I think people are more likely to try out a program if they can see how the program looks. Even if they don't try it, it's still nice to be able to see someone's accomplishment.

It would be great to see a screenshot in your readme.md file if you have time to add something. It's really easy with GitHub to embed an image. All you have to do is grab and drop or copy and paste your image into an Issue, just like the one this message is in, and then copy / paste the code that's created by GitHub into you readme.md file. The same code that embeds an image into an Issue can be used to embed the image into the readme.md file.

Thanks for your time and sharing your code on GitHub.

**Comment by pizzaspren** [comment]
Hi @PySimpleGUI 
There are screenshots already uploaded in the Readme file. You just need to open the `GUI Images` dropdown.

**Comment by PySimpleGUI** [comment]
Oh, I see.... hmmm.... it was very very easy for me to miss.  Any particular reason it starts out as collapsed?  Why hide them or make it so that the user has to scan the readme to find this arrow?  I would have already moved on before trying to find the images.

**Comment by PySimpleGUI** [comment]
> The images are also being updated every time there is a visual change in the program.

Oooooo.... I missed that part of your answer.... need to look at how you did that!

**Comment by pizzaspren** [comment]
> Any particular reason it starts out as collapsed?

That's just how Github has chosen to implement the _details_ html tag unfortunately.

> Why hide them or make it so that the user has to scan the readme to find this arrow? I would have already moved on before trying to find the images.

They take up a fair bit of space and I am not exactly proud of my layout skills. Moreover, the dropdown is on the second line of the Readme file. I guess I can add something to show it can be interacted with.

> Oooooo.... I missed that part of your answer.... need to look at how you did that!

Manually, changing the images in `assets/images` folder :)

**Comment by PySimpleGUI** [comment]
I like the new format where it's shown automatically and can be collapsed.

Nothing to be ashamed about your layout.  You can refine how it looks over time.  Lots of different color themes you can try out for example.  Any GUI in Python is a good GUI in Python.  Seriously.  It's not done very often and the result is that "normal people" miss out on a lot of good tools.  Showing your project has a GUI grabs the visitors attention, right away.

But, that's just my opinion :-)  I think you've got plenty to be proud of with your GUI 👍
